.build: &build
  image: alonid/rockylinux-rpm-builder:8.6.20227707
  stage: build
  interruptible: true


build_and_upload:
  <<: *build
  variables:
    VASTDB_APPEND_VERSION_SUFFIX: 'true'
  script:
    - pip3 install wheel
    - python3 setup.py bdist_wheel
    - ./upload.sh
  tags:
    - vast-dev-builder


check_latest_python:
  <<: *build
  script:
    - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - yum install -y docker-ce
    - docker build -f Dockerfile .
  tags:
    - vast-dev-builder
